source 'https://rubygems.org'
gem 'rails', '4.2.4'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'rails_admin'
gem 'bootstrap-sass'
gem 'devise'
gem 'devise_token_auth'
gem 'administrate'
gem 'rack-cors', :require => 'rack/cors'
group :development, :test do
  gem 'byebug'
  gem 'sqlite3'
end
group :development do
  gem 'pry'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'better_errors'
  gem 'quiet_assets'
  gem 'rails_layout'
  gem 'pg'
end
group :production do
  gem 'thin'
end
